version: '3.8'

services:
  dev:
    container_name: rbh_consumer_app
    image: rbh_consumer_app:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    depends_on: 
      - redis
    volumes:
      - .:/usr/src/app
      - ./node_modules:/app/node_modules
    restart: unless-stopped

  redis: # Example Service
    container_name: consumer_app_redis
    restart: always
    image: redis:6.0-alpine
    ports:
    - "6379:6379"
    volumes:
      - consumer_app_redis_data:/data

volumes:
  consumer_app_redis_data:

networks:
  default:
    external:
      name: myapp